spring:
  application:
    name: reservations

  datasource:
    url: jdbc:h2:mem:reservationsdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
